'use client'

import React, { createContext, useContext, useState, useEffect } from 'react'

type Language = 'ko' | 'en'

interface LanguageContextType {
  language: Language
  setLanguage: (lang: Language) => void
  t: (key: string) => string
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

// 번역 데이터
const translations = {
  ko: {
    // 네비게이션
    'nav.features': '기능',
    'nav.specs': '사양',
    'nav.gallery': '갤러리',
    'nav.pricing': '가격',
    'nav.buy': '구매하기',
    'nav.home': '홈으로',
    
    // 메인 페이지
    'hero.title': 'TechPro Max',
    'hero.subtitle': '혁신적인 기술과 세련된 디자인이 만나 완성된 프리미엄 디바이스',
    'hero.buy': '지금 구매하기',
    'hero.learn': '더 알아보기',
    
    // 기능 섹션
    'features.title': '혁신적인 기능',
    'features.subtitle': 'TechPro Max의 놀라운 기능들을 만나보세요',
    'features.ai.title': 'AI 기능',
    'features.ai.desc': '실시간 통역, 이미지 생성,<br/>음성비서 등 강력한 AI 기능',
    'features.ai.section.title': 'AI 기능',
    'features.camera.title': '프로급 카메라',
    'features.camera.desc': '4,800만화소 트리플 카메라로 완벽한 사진 촬영',
    'features.performance.title': '최고 성능',
    'features.performance.desc': 'A19 Pro 프로세서로 모든 작업을 빠르게 처리',
    'features.design.title': '세련된 디자인',
    'features.design.desc': 'IP68 방수 등급과 프리미엄 소재로 완성된 디자인',
    
    // 사양 섹션
    'specs.title': '기술 사양',
    'specs.subtitle': 'TechPro Max의 상세한 기술 사양을 확인하세요',
    'specs.display': '화면',
    'specs.storage': '용량',
    'specs.processor': '프로세서',
    'specs.camera': '카메라',
    'specs.battery': '배터리',
    'specs.dimensions': '규격',
    'specs.ai': 'AI 기능',
    'specs.display.size': '화면 크기',
    'specs.display.value': '17.4cm (6.9인치)',
    'specs.dimensions.width': '가로',
    'specs.dimensions.height': '세로',
    'specs.dimensions.thickness': '두께',
    'specs.dimensions.weight': '무게',
    'specs.dimensions.width.value': '78mm',
    'specs.dimensions.height.value': '163.4mm',
    'specs.dimensions.thickness.value': '8.75mm',
    'specs.dimensions.weight.value': '231g',
    'specs.performance.title': '성능 & 저장',
    'specs.processor.value': 'A19 Pro',
    'specs.storage.value': '256GB',
    'specs.communication': '통신',
    'specs.communication.value': '5G',
    'specs.waterproof': '방수',
    'specs.waterproof.value': 'IP68',
    'specs.camera.title': '카메라 & 배터리',
    'specs.camera.rear': '후면 카메라',
    'specs.camera.rear.value': '4,800만화소 × 3',
    'specs.camera.front': '전면 카메라',
    'specs.camera.front.value': '1,800만화소',
    'specs.charging': '충전',
    'specs.charging.value': 'USB3.2',
    'specs.magsafe': '맥세이프',
    'specs.magsafe.value': '최대 25W',
    'specs.ai.summary': '요약',
    'specs.ai.edit': '편집',
    'specs.ai.correction': '교정',
    'specs.ai.imagegen': '이미지 생성',
    'specs.ai.imageedit': '이미지 편집',
    'specs.ai.translation': '실시간 통역',
    'specs.ai.voice': '음성비서',
    'specs.ai.processor': 'AI 프로세서',
    
    // 갤러리 섹션
    'gallery.title': '갤러리',
    'gallery.subtitle': 'TechPro Max의 다양한 모습을 확인하세요',
    'gallery.product': '제품',
    'gallery.ai': 'AI 데모',
    'gallery.camera': '카메라 샘플',
    'gallery.ux': '사용자 경험',
    'gallery.detail': '상세 갤러리',
    'gallery.product.title': '제품 갤러리',
    'gallery.ai.title': 'AI 기능 데모',
    'gallery.camera.title': '카메라 샘플',
    'gallery.ux.title': '사용자 경험',
    'gallery.detail.title': '디테일 갤러리',
    'gallery.product.front': '정면 뷰',
    'gallery.product.orange': '오렌지 컬러',
    'gallery.product.darkblue': '다크 블루',
    'gallery.product.white': '화이트 컬러',
    'gallery.ai.translation': '실시간 통역',
    'gallery.ai.translation.desc': '다국어 실시간 번역 기능',
    'gallery.ai.imagegen': '이미지 생성',
    'gallery.ai.imagegen.desc': 'AI로 생성한 이미지들',
    'gallery.ai.voice': '음성비서',
    'gallery.ai.voice.desc': '스마트 음성 어시스턴트',
    'gallery.camera.landscape': '풍경 사진',
    'gallery.camera.portrait': '인물 사진',
    'gallery.camera.night': '야간 촬영',
    'gallery.camera.macro': '매크로 촬영',
    'gallery.camera.landscape.desc': '4,800만화소',
    'gallery.camera.portrait.desc': 'AI 인물 모드',
    'gallery.camera.night.desc': '야간 모드',
    'gallery.camera.macro.desc': '초근접 촬영',
    'gallery.ux.home': '홈 화면',
    'gallery.ux.multitask': '멀티태스킹',
    'gallery.ux.gaming': '게임 플레이',
    'gallery.ux.home.desc': '직관적인 사용자 인터페이스',
    'gallery.ux.multitask.desc': '효율적인 작업 관리',
    'gallery.ux.gaming.desc': '부드러운 게임 경험',
    'gallery.detail.camera': '카메라 모듈',
    'gallery.detail.buttons': '사이드 버튼',
    'gallery.detail.port': '충전 포트',
    'gallery.detail.speaker': '스피커 그릴',
    
    // 가격 섹션
    'pricing.title': '가격',
    'pricing.subtitle': 'TechPro Max의 가격을 확인하세요',
    'pricing.price': '₩1,990,000',
    'pricing.launch': '출시가',
    'pricing.buy': '구매하기',
    'pricing.techpro.price': '₩1,200,000',
    'pricing.techpromax.price': '₩1,990,000',
    'pricing.techproultra.price': '₩1,800,000',
    'pricing.storage.128': '128GB 저장공간',
    'pricing.storage.256': '256GB 저장공간',
    'pricing.storage.512': '512GB 저장공간',
    'pricing.display.6.1': '6.1인치 디스플레이',
    'pricing.display.6.9': '6.9인치 디스플레이',
    'pricing.display.6.7': '6.7인치 디스플레이',
    'pricing.camera.basic': '기본 카메라',
    'pricing.camera.48mp': '4,800만화소 카메라 × 3',
    'pricing.camera.ultra': '울트라 카메라',
    'pricing.processor.a19': 'A19 Pro 프로세서',
    'pricing.ai.builtin': 'AI 기능 내장',
    'pricing.popular': '인기',
    'pricing.select': '선택하기',
    
    // 구매 페이지
    'purchase.title': 'TechPro 구매',
    'purchase.subtitle': '원하는 모델을 선택하고 구매하세요',
    'purchase.select': '제품 선택',
    'purchase.techpro': 'TechPro',
    'purchase.techpromax': 'TechPro Max',
    'purchase.techproultra': 'TechPro Ultra',
    'purchase.recommended': '추천',
    'purchase.select_btn': '선택하기',
    'purchase.info': '구매 정보',
    'purchase.name': '이름',
    'purchase.phone': '전화번호',
    'purchase.email': '이메일',
    'purchase.address': '주소',
    'purchase.payment': '결제 방법',
    'purchase.total': '총 결제 금액',
    'purchase.order': '주문하기',
    'purchase.hero.title': 'TechPro Max 구매',
    'purchase.hero.subtitle': '프리미엄 스마트폰을 지금 바로 주문하세요',
    'purchase.techpro.title': 'TechPro 스마트폰',
    'purchase.techpromax.title': 'TechPro Max 스마트폰',
    'purchase.techproultra.title': 'TechPro Ultra 스마트폰',
    'purchase.techpro.price': '₩1,200,000',
    'purchase.techpromax.price': '₩1,990,000',
    'purchase.techproultra.price': '₩2,500,000',
    'purchase.techpro.storage': '128GB 저장공간',
    'purchase.techpromax.storage': '256GB 저장공간',
    'purchase.techproultra.storage': '512GB 저장공간',
    'purchase.techpro.display': '6.1인치 디스플레이',
    'purchase.techpromax.display': '6.9인치 디스플레이',
    'purchase.techproultra.display': '6.9인치 디스플레이',
    'purchase.techpro.camera': '기본 카메라',
    'purchase.techpromax.camera': '4,800만화소 카메라 × 3',
    'purchase.techproultra.camera': '울트라 카메라',
    'purchase.techpro.processor': 'A17 프로세서',
    'purchase.techpromax.processor': 'A19 Pro 프로세서',
    'purchase.techproultra.processor': 'A19 Pro Max 프로세서',
    'purchase.techpro.ai': '',
    'purchase.techpromax.ai': 'AI 기능 내장',
    'purchase.techproultra.ai': '프리미엄 AI 기능',
    'purchase.info.title': '구매 정보 입력',
    'purchase.name.placeholder': '홍길동',
    'purchase.phone.placeholder': '010-1234-5678',
    'purchase.email.placeholder': 'example@email.com',
    'purchase.address.placeholder': '서울시 강남구 테헤란로 123, 456동 789호',
    'purchase.payment.credit': '신용카드',
    'purchase.payment.transfer': '계좌이체',
    'purchase.payment.kakao': '카카오페이',
    
    // 지원 페이지
    'support.title': '고객 지원',
    'support.subtitle': 'TechPro와 함께하는 모든 순간을 지원합니다',
    'support.faq': '자주 묻는 질문',
    'support.guide': '사용 가이드',
    'support.warranty': '보증 정보',
    'support.downloads': '다운로드',
    
    // 푸터
    'footer.company': 'TechPro Inc.',
    'footer.rights': '모든 권리 보유.',
    'footer.privacy': '개인정보처리방침',
    'footer.terms': '이용약관',
    'footer.contact': '문의하기',
    'footer.subtitle': '혁신적인 기술로 만든 프리미엄 디바이스',
    'footer.product': '제품',
    'footer.techpro': 'TechPro',
    'footer.techpromax': 'TechPro Max',
    'footer.techproultra': 'TechPro Ultra',
    'footer.support': '지원',
    'footer.customer': '고객지원',
    'footer.repair': '수리서비스',
    'footer.warranty': '보증',
    'footer.company_info': '회사',
    'footer.about': '회사소개',
    'footer.careers': '채용정보',
    'footer.news': '뉴스',
    'footer.purchase': '안전한 결제와 빠른 배송을 약속드립니다.'
  },
  en: {
    // 네비게이션
    'nav.features': 'Features',
    'nav.specs': 'Specs',
    'nav.gallery': 'Gallery',
    'nav.pricing': 'Pricing',
    'nav.buy': 'Buy Now',
    'nav.home': 'Home',
    
    // 메인 페이지
    'hero.title': 'TechPro Max',
    'hero.subtitle': 'Innovative technology meets sophisticated design in the ultimate premium device',
    'hero.buy': 'Buy Now',
    'hero.learn': 'Learn More',
    
    // 기능 섹션
    'features.title': 'Innovative Features',
    'features.subtitle': 'Discover the amazing features of TechPro Max',
    'features.ai.title': 'AI Features',
    'features.ai.desc': 'Powerful AI features including real-time translation, image generation, and voice assistant',
    'features.ai.section.title': 'AI Features',
    'features.camera.title': 'Pro Camera',
    'features.camera.desc': 'Perfect photography with 48MP triple camera system',
    'features.performance.title': 'Ultimate Performance',
    'features.performance.desc': 'Handle all tasks quickly with A19 Pro processor',
    'features.design.title': 'Elegant Design',
    'features.design.desc': 'Premium design with IP68 water resistance and premium materials',
    
    // 사양 섹션
    'specs.title': 'Technical Specifications',
    'specs.subtitle': 'Check out the detailed technical specifications of TechPro Max',
    'specs.display': 'Display',
    'specs.storage': 'Storage',
    'specs.processor': 'Processor',
    'specs.camera': 'Camera',
    'specs.battery': 'Battery',
    'specs.dimensions': 'Dimensions',
    'specs.ai': 'AI Features',
    'specs.display.size': 'Screen Size',
    'specs.display.value': '17.4cm (6.9 inches)',
    'specs.dimensions.width': 'Width',
    'specs.dimensions.height': 'Height',
    'specs.dimensions.thickness': 'Thickness',
    'specs.dimensions.weight': 'Weight',
    'specs.dimensions.width.value': '78mm',
    'specs.dimensions.height.value': '163.4mm',
    'specs.dimensions.thickness.value': '8.75mm',
    'specs.dimensions.weight.value': '231g',
    'specs.performance.title': 'Performance & Storage',
    'specs.processor.value': 'A19 Pro',
    'specs.storage.value': '256GB',
    'specs.communication': 'Connectivity',
    'specs.communication.value': '5G',
    'specs.waterproof': 'Water Resistance',
    'specs.waterproof.value': 'IP68',
    'specs.camera.title': 'Camera & Battery',
    'specs.camera.rear': 'Rear Camera',
    'specs.camera.rear.value': '48MP × 3',
    'specs.camera.front': 'Front Camera',
    'specs.camera.front.value': '18MP',
    'specs.charging': 'Charging',
    'specs.charging.value': 'USB3.2',
    'specs.magsafe': 'MagSafe',
    'specs.magsafe.value': 'Up to 25W',
    'specs.ai.summary': 'Summary',
    'specs.ai.edit': 'Edit',
    'specs.ai.correction': 'Correction',
    'specs.ai.imagegen': 'Image Generation',
    'specs.ai.imageedit': 'Image Editing',
    'specs.ai.translation': 'Real-time Translation',
    'specs.ai.voice': 'Voice Assistant',
    'specs.ai.processor': 'AI Processor',
    
    // 갤러리 섹션
    'gallery.title': 'Gallery',
    'gallery.subtitle': 'Explore the various aspects of TechPro Max',
    'gallery.product': 'Product',
    'gallery.ai': 'AI Demo',
    'gallery.camera': 'Camera Samples',
    'gallery.ux': 'User Experience',
    'gallery.detail': 'Detail Gallery',
    'gallery.product.title': 'Product Gallery',
    'gallery.ai.title': 'AI Features Demo',
    'gallery.camera.title': 'Camera Samples',
    'gallery.ux.title': 'User Experience',
    'gallery.detail.title': 'Detail Gallery',
    'gallery.product.front': 'Front View',
    'gallery.product.orange': 'Orange Color',
    'gallery.product.darkblue': 'Dark Blue',
    'gallery.product.white': 'White Color',
    'gallery.ai.translation': 'Real-time Translation',
    'gallery.ai.translation.desc': 'Multilingual real-time translation feature',
    'gallery.ai.imagegen': 'Image Generation',
    'gallery.ai.imagegen.desc': 'AI-generated images',
    'gallery.ai.voice': 'Voice Assistant',
    'gallery.ai.voice.desc': 'Smart voice assistant',
    'gallery.camera.landscape': 'Landscape Photos',
    'gallery.camera.portrait': 'Portrait Photos',
    'gallery.camera.night': 'Night Photography',
    'gallery.camera.macro': 'Macro Photography',
    'gallery.camera.landscape.desc': '48MP',
    'gallery.camera.portrait.desc': 'AI Portrait Mode',
    'gallery.camera.night.desc': 'Night Mode',
    'gallery.camera.macro.desc': 'Ultra-close Photography',
    'gallery.ux.home': 'Home Screen',
    'gallery.ux.multitask': 'Multitasking',
    'gallery.ux.gaming': 'Gaming Experience',
    'gallery.ux.home.desc': 'Intuitive user interface',
    'gallery.ux.multitask.desc': 'Efficient task management',
    'gallery.ux.gaming.desc': 'Smooth gaming experience',
    'gallery.detail.camera': 'Camera Module',
    'gallery.detail.buttons': 'Side Buttons',
    'gallery.detail.port': 'Charging Port',
    'gallery.detail.speaker': 'Speaker Grill',
    
    // 가격 섹션
    'pricing.title': 'Pricing',
    'pricing.subtitle': 'Check out the pricing for TechPro Max',
    'pricing.price': '$1,499',
    'pricing.launch': 'Launch Price',
    'pricing.buy': 'Buy Now',
    'pricing.techpro.price': '$899',
    'pricing.techpromax.price': '$1,499',
    'pricing.techproultra.price': '$1,299',
    'pricing.storage.128': '128GB Storage',
    'pricing.storage.256': '256GB Storage',
    'pricing.storage.512': '512GB Storage',
    'pricing.display.6.1': '6.1-inch Display',
    'pricing.display.6.9': '6.9-inch Display',
    'pricing.display.6.7': '6.7-inch Display',
    'pricing.camera.basic': 'Basic Camera',
    'pricing.camera.48mp': '48MP Camera × 3',
    'pricing.camera.ultra': 'Ultra Camera',
    'pricing.processor.a19': 'A19 Pro Processor',
    'pricing.ai.builtin': 'Built-in AI Features',
    'pricing.popular': 'Popular',
    'pricing.select': 'Select',
    
    // 구매 페이지
    'purchase.title': 'TechPro Purchase',
    'purchase.subtitle': 'Choose your desired model and make a purchase',
    'purchase.select': 'Product Selection',
    'purchase.techpro': 'TechPro',
    'purchase.techpromax': 'TechPro Max',
    'purchase.techproultra': 'TechPro Ultra',
    'purchase.recommended': 'Recommended',
    'purchase.select_btn': 'Select',
    'purchase.info': 'Purchase Information',
    'purchase.name': 'Name',
    'purchase.phone': 'Phone',
    'purchase.email': 'Email',
    'purchase.address': 'Address',
    'purchase.payment': 'Payment Method',
    'purchase.total': 'Total Amount',
    'purchase.order': 'Place Order',
    'purchase.hero.title': 'TechPro Max Purchase',
    'purchase.hero.subtitle': 'Order your premium smartphone now',
    'purchase.techpro.title': 'TechPro Smartphone',
    'purchase.techpromax.title': 'TechPro Max Smartphone',
    'purchase.techproultra.title': 'TechPro Ultra Smartphone',
    'purchase.techpro.price': '$899',
    'purchase.techpromax.price': '$1,499',
    'purchase.techproultra.price': '$1,899',
    'purchase.techpro.storage': '128GB Storage',
    'purchase.techpromax.storage': '256GB Storage',
    'purchase.techproultra.storage': '512GB Storage',
    'purchase.techpro.display': '6.1-inch Display',
    'purchase.techpromax.display': '6.9-inch Display',
    'purchase.techproultra.display': '6.9-inch Display',
    'purchase.techpro.camera': 'Basic Camera',
    'purchase.techpromax.camera': '48MP Camera × 3',
    'purchase.techproultra.camera': 'Ultra Camera',
    'purchase.techpro.processor': 'A17 Processor',
    'purchase.techpromax.processor': 'A19 Pro Processor',
    'purchase.techproultra.processor': 'A19 Pro Max Processor',
    'purchase.techpro.ai': '',
    'purchase.techpromax.ai': 'Built-in AI Features',
    'purchase.techproultra.ai': 'Premium AI Features',
    'purchase.info.title': 'Purchase Information',
    'purchase.name.placeholder': 'John Doe',
    'purchase.phone.placeholder': '+1-234-567-8900',
    'purchase.email.placeholder': 'example@email.com',
    'purchase.address.placeholder': '123 Main St, City, State 12345',
    'purchase.payment.credit': 'Credit Card',
    'purchase.payment.transfer': 'Bank Transfer',
    'purchase.payment.kakao': 'KakaoPay',
    
    // 지원 페이지
    'support.title': 'Customer Support',
    'support.subtitle': 'We support every moment with TechPro',
    'support.faq': 'FAQ',
    'support.guide': 'User Guide',
    'support.warranty': 'Warranty',
    'support.downloads': 'Downloads',
    
    // 푸터
    'footer.company': 'TechPro Inc.',
    'footer.rights': 'All rights reserved.',
    'footer.privacy': 'Privacy Policy',
    'footer.terms': 'Terms of Service',
    'footer.contact': 'Contact Us',
    'footer.subtitle': 'Premium device made with innovative technology',
    'footer.product': 'Products',
    'footer.techpro': 'TechPro',
    'footer.techpromax': 'TechPro Max',
    'footer.techproultra': 'TechPro Ultra',
    'footer.support': 'Support',
    'footer.customer': 'Customer Support',
    'footer.repair': 'Repair Service',
    'footer.warranty': 'Warranty',
    'footer.company_info': 'Company',
    'footer.about': 'About Us',
    'footer.careers': 'Careers',
    'footer.news': 'News',
    'footer.purchase': 'We promise secure payment and fast delivery.'
  }
}

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('ko')

  useEffect(() => {
    const savedLanguage = localStorage.getItem('language') as Language
    if (savedLanguage && (savedLanguage === 'ko' || savedLanguage === 'en')) {
      setLanguage(savedLanguage)
    }
  }, [])

  const handleSetLanguage = (lang: Language) => {
    setLanguage(lang)
    localStorage.setItem('language', lang)
  }

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations[typeof language]] || key
  }

  return (
    <LanguageContext.Provider value={{ language, setLanguage: handleSetLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export const useLanguage = () => {
  const context = useContext(LanguageContext)
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider')
  }
  return context
}
